### ISSUE TITLE
tabufline broke, then the whole config did

### ISSUE THREAD

**Issue by cctrc** [mgastonportillo/nvchad-config#1]
can i please get the files for the new nvim update? i think that broke it

**Comment by mgastonportillo** [comment]
Hey there, I'm afraid I don't plan to update my config. I don't have the time to do so. Stick to 2.0 if you want to use my config, or run a different setup for 2.5. The main feature of 2.5 is that it is now an embeddable config, which changes a lot of stuff.

**Comment by mgastonportillo** [comment]
I just realised you said nvim and not nvchad. Stick to the recommended version of nvim for nvchad. It's on their end whether to support a recent nvim version or not. I can't do anything if a specific version of nvchad doesn't work with your version of nvim

**Comment by cctrc** [comment]
i had meant nvchad. Sadly i cannot find the 2.0 NvChad release again. Thank you for your response!

**Comment by mgastonportillo** [comment]
Oh, you can install it via these commands:
```bash
cd $HOME/.config/nvim
git clone -b 2.0 https://github.com/NvChad/NvChad
```
Just make sure to backup whatever you currently have at `$HOME/.config/nvim` (or to remove it)

Although, soon I will update my config. The update process seems less complicated than I initially thought

**Comment by mgastonportillo** [comment]
I updated the config @cctrc, just be aware that it might contain bugs. Let me know if you find any, in case that you decide to use it
