### ISSUE TITLE
is your dap-ui config correct? I am getting error saying module dap not found.

### ISSUE THREAD

**Issue by aasutossh** [mgastonportillo/nvchad-config#2]
![image](https://github.com/mgastonportillo/nvchad-config/assets/18498932/90de95d0-6bb8-4e5d-9204-6b4c0de68531)

**Comment by mgastonportillo** [comment]
I disabled the plugin because I was getting a dependency error with `nvim-nio`. I didn't have time to debug it. By now, I'd suggest just disabling it. Are you using the latest v2.5 config?

**Comment by aasutossh** [comment]
yes.

**Comment by aasutossh** [comment]
I cloned the starter, and using things from your config.

**Comment by mgastonportillo** [comment]
According to your error, try copying the dap dependency from `plugins/gale/dap-ui.lua` into its own import in `plugins/init.lua`

**Comment by aasutossh** [comment]
I commented the require portions, it installs the plugins, after that I uncomment the require portions, it still gave me error. trying this.

**Comment by mgastonportillo** [comment]
Did you remove/rename the `.local/share/nvim` folder before installing v2.5? Could be the culprit.

I'll try to get dap-ui working soon in my config.

**Comment by aasutossh** [comment]
I installed it in nvim-chad directory in my config.

**Comment by aasutossh** [comment]
I'll comment it all out for now. Will inform if I make it work.

**Comment by mgastonportillo** [comment]
> I installed it in nvim-chad directory in my config.

Did you follow the [uninstall steps](https://nvchad.com/docs/quickstart/install) at the bottom first?

**Comment by aasutossh** [comment]
Let me try it again, but I did things right.

**Comment by mgastonportillo** [comment]
@aasutossh should be fixed now. If you run into any error, try a clean install.

**Comment by aasutossh** [comment]
Will try in the evening and then report back :)
