### ISSUE TITLE
 attempt to index field 'uv' (a nil value)

### ISSUE THREAD

**Issue by slpzc** [mgastonportillo/nvchad-config#4]
Error: 
E5113: Error while calling lua chunk: C:\Users\root\AppData\Local\nvim/lua/bootstrap.lua:6: attempt to index field 'uv' (a nil value)
stack traceback:
        C:\Users\root\AppData\Local\nvim/lua/bootstrap.lua:6: in main chunk
        [C]: in function 'require'
        C:\Users\root\AppData\Local\nvim\init.lua:2: in main chunk

What I did:
1) Downloaded the repository archive;
2) Unpacked all the contents into the nvim folder;
3) Run the command "nvim".

**Comment by mgastonportillo** [comment]
Hey @slpzc, are you on neovim 0.10? It needs the latest stable build, as specified in the readme. `vim.loop` got deprecated and `vim.uv` is preferred

**Comment by slpzc** [comment]
> Hey @slpzc, are you on neovim 0.10? It needs the latest stable build, as specified in the readme. `vim.loop` got deprecated and `vim.uv` is preferred

I apologize, it's my mistake. Indeed, neovim was a lower version (0.9.5)

However, after doing all the same steps, I get this error:
An error was detected while processing VimEnter Auto Commands for "*":
Lua module not found for config of cd-project.nvim. Please use a `config()` function instead

**Comment by mgastonportillo** [comment]
I'll get back to you in a couple hours. Travelling right now. I might have made a mistake with `cd-project`'s spec. Thanks for reporting it.

**Comment by mgastonportillo** [comment]
@slpzc should be fixed now. I accidentally left some specs defined as local dev. If you find any other issue related to this, please remove the contents of the `plugins/local` folder and run `:SrcPlugins` then re-open neovim. I'll add proper handlers for this soon. Sorry for the inconveniences

**Comment by slpzc** [comment]
> @slpzc should be fixed now. I accidentally left some specs defined as local dev. If you find any other issue related to this, please remove the contents of the `plugins/local` folder and run `:SrcPlugins` then re-open neovim. I'll add proper handlers for this soon. Sorry for the inconveniences

I reinstalled it, ran it and got an error:

Failed to run `config` for nvim-notify cannot open C:\Users\root\AppData\Local\nvim-data/nvchad/base46/notify: No such file or directory # stacktrace: - AppData/Local/nvim/lua/plugins/spec/notify.lua:5 _in_ **config** 

Then, tried deleting the contents of `plugins/local` and restarting got errors:

An error was detected while processing C:\Users\root\AppData\Local\nvim\init.lua:
No specs found for module plugins.local.binary-peek No specs found for module plugins.local.flip-flop No specs found for module plugins.local.js-playground No specs found for module plugins.local.popurri No specs found for module plugins.local.yerbreak

When trying to run `:SrcPlugins` it gives an error:
Config Change Detected. Reloading...                                                                                                                                                                                                          - **changed**: AppData/Local/nvim/lua/plugins/init.lua.

**Comment by mgastonportillo** [comment]
@slpzc the last message: `Config Change Detected. Reloading... - changed: AppData/Local/nvim/lua/plugins/init.lua` isn't an error. That is a reloading message which happens because the `plugins/init.lua` file has been changed. After re-opening neovim, lazy.nvim will detect the changes and proceed accordingly.

Somehow you are trying to access configurations in the Windows filesystem: `Failed to run config for nvim-notify cannot open C:\Users\root\AppData\Local\nvim-data/nvchad/base46/notify: No such file or directory # stacktrace: - AppData/Local/nvim/lua/plugins/spec/notify.lua:5 in config`

WSL uses the linux file system, so I think you're making a mistake in the way you're installing neovim.

**Comment by mgastonportillo** [comment]
@slpzc I'll be closing the issue, but feel free to re-open it if you have more questions. Hopefully you were able to make it work.
