### ISSUE TITLE
Awesome config man, what font are you using?

### ISSUE THREAD

**Issue by dev-xero** [mgastonportillo/nvchad-config#6]
The icons on the bottom seem to be broken, I think that's because of the font I'm using (JetBrains Mono).  I'm pretty new to neovim btw.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/dda88532-c983-46d9-b599-e4a6718a0201">

**Comment by mgastonportillo** [comment]
I'm using JetBrains Mono as well, but patched (nerd fonts). Try any font from nerd fonts and let me know if the issue still persists. I'll take a look 👍

**Comment by mgastonportillo** [comment]
Are you installing any statusline plugin?

**Comment by dev-xero** [comment]
> Are you installing any statusline plugin?

I don't think so. I just git cloned your configs into mine.

**Comment by dev-xero** [comment]
> I'm using JetBrains Mono as well, but patched (nerd fonts). Try any font from nerd fonts and let me know if the issue still persists. I'll take a look 👍

alright, i'll try that, thanks.

**Comment by mgastonportillo** [comment]
Nerd fonts are a requirement for NvChad. I'll make sure to add any missing requirements to my readme. Thanks for reporting the issue!

**Comment by dev-xero** [comment]
ok, i installed the nerd font and synced up a bunch of stuff. statusline is working now.

<img width="951" alt="image" src="https://github.com/user-attachments/assets/3557eb04-a245-4eb9-88a6-e7275f46c7ed">

but then i get this error when switching themes:

E5108: Error executing lua: /home/****/.config/nvim/lua/chadrc.lua:38: attempt to index local 'themed_values' (a ni
l value)
stack traceback:
        /home/****/.config/nvim/lua/chadrc.lua:38: in main chunk
        [C]: in function 'dofile'
        .../share/nvim/lazy/ui/lua/telescope/_extensions/themes.lua:66: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:293: in function <...hare/nvim/lazy/telescope.n
vim/lua/telescope/mappings.lua:292>

**Comment by dev-xero** [comment]
<img width="661" alt="image" src="https://github.com/user-attachments/assets/0341f1b3-a68f-41cf-8111-4d47fe16fe31">

it's also probably related to this.

**Comment by dev-xero** [comment]
yeah, this line in particular since the `chadrc_aux` file custom themes doesn't have a catppuccin key

<img width="578" alt="image" src="https://github.com/user-attachments/assets/a641667f-3649-4ace-b5d4-b67ecf384f10">

<img width="777" alt="image" src="https://github.com/user-attachments/assets/136f3569-d824-4cc4-b4e0-ae1b62a43846">

**Comment by mgastonportillo** [comment]
Yeah, sorry about that one, I'm working on a theme port and didn't account for other themes while implementing it. I'll push a fix soon

**Comment by dev-xero** [comment]
alright sweet. loving your config btw. 💯
