### ISSUE TITLE
[BUG] Rustacean + nvim cmp not working

### ISSUE THREAD

**Issue by lekhanhtoan37** [mgastonportillo/nvchad-config#9]
### **Describe the bug**
Using rustacean or rust-tools will break nvim cmp. There is no suggestion prompt/completion at all (except supermaven suggestion)

### **To Reproduce**
1. Rust file with `Cargo.toml` in root folder
2. Typing
3. See error

### **Expected behavior**
Completion/Suggestion works like gofmt.

### **Screenshots**
<img width="692" alt="Screenshot 2024-12-16 at 17 49 53" src="https://github.com/user-attachments/assets/e29b57f1-76cc-4476-9c2f-897e88833306" />

### **Specs (please complete the following information
 - OS: macos 15.1.1 (24B91)
 - Neovim version: 
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
 - rust-analyzer: 1.83.0 (90b35a62 2024-11-26)
 - rustc 1.83.0 (90b35a623 2024-11-26)

### **Additional context**
NA

**Comment by mgastonportillo** [comment]
I'll take a look as soon as possible. Thanks for the detailed issue!

**Comment by mgastonportillo** [comment]
Was just taking a quick look and things seem to be working just fine for me:
![image](https://github.com/user-attachments/assets/bdb0fb66-2579-49e4-b094-af37006749e9)

Have you tried `:Lazy sync`? I'll push an updated version of the config in a minute, but there's no changes related to Rust if my memory doesn't trick me

**Comment by mgastonportillo** [comment]
Wonderful, thanks again for the detailed answer. I'll check crates docs/repo and see if this might cause any issues. If it doesn't, then I'll apply your patch to the config 👍

**Comment by mgastonportillo** [comment]
Updated the configs related to rust to match the latest versions of rustaceanvim and crates. Tested everything and it seems to work as intended. Feel free to reopen the issue if you notice anything wrong
